# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T18:58:35+00:00

from __future__ import annotations

from datetime import date
from typing import Optional

from pydantic import BaseModel


class SearchGetResponse(BaseModel):
    company_name: Optional[str] = None
    environment_score: Optional[float] = None
    governance_score: Optional[float] = None
    last_processing_date: Optional[date] = None
    social_score: Optional[float] = None
    total: Optional[float] = None
